version: '3.5'

services:
  mybpo-nginx:
    image: nginx:latest
    container_name: mybpo-nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - mybpo
    networks:
      tredo:
        aliases:
          - mybpo.loc
    command: [nginx-debug, '-g', 'daemon off;']

  mybpo:
    build:
      context: ./../mybpo-backend
      args:
        user: www-data
        uid: 1000
      dockerfile: ./../docker/php.dockerfile
    volumes:
      -  /Users/ak/projects/tredo/mybpo-backend:/srv/www/app
      - ./../docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - tredo
    depends_on:
      - database
    container_name: mybpo

  database:
    hostname: database.loc
    container_name: mariadb
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/dump:/srv/dump
    ports:
      - "3306:3306"
    networks:
      - tredo

networks:
  tredo:
    driver: bridge
